### PR TITLE
add Coinmap

### PR DESCRIPTION
**Pull request by prusnak**
map visualizing venues where one can pay with Bitcoins

### CODE REVIEW

**Comment by elving** [comment]
Hi @prusnak. Can you add a photo that shows more of the UI like the one above?

screen shot 2015-08-28 at 10 11 17 am

**Comment by prusnak** [comment]
updated PR

**Comment by elving** [comment]
@prusnak :+1: Thanks!

**Comment by musicformellons** [comment]
@prusnak I found a reference to a repo but it seems that is not the actual react code; is it?
https://github.com/hivewallet/coinmap

**Comment by prusnak** [comment]
No. This is a fork of old version which was not built with React. New version is not open source.

**Pull request merged**
